Conditional upload of MLTBX

diff --git a/.github/workflows/upload-artifact.yml b/.github/workflows/upload-artifact.yml
--- a/.github/workflows/upload-artifact.yml
+++ b/.github/workflows/upload-artifact.yml
@@ -33,7 +33,16 @@ jobs:
           draft: false
           prerelease: false
 
+      # Forks of this repo can have failed to build the MLTBX output so conditionally check for its 
+      # existence and let other steps know about this.
+      - name: Check MLTBX file exists
+        id: mltbx-check
+        shell: bash
+        run: |
+          echo ::set-output name=exist::((test -f ./bin/FSDA.mltbx && echo true) || echo false)
+
       - name: Upload Release Asset
+        if: ${{ steps.mltbx-check.outputs.exist == true }}
         id: upload-release-asset 
         uses: actions/upload-release-asset@v1
         env:
@@ -42,15 +51,15 @@ jobs:
         with:
           #upload_url: github.event.release.upload_url
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./license.txt
-          asset_name: LICENSE
-          asset_content_type: text/plain
+          asset_path: ./bin/FSDA.mltbx
+          asset_name: FSDA.mltbx
+          asset_content_type: application/gzip
 
       - name: Extract tag from this release
+        id: extract_tag
         shell: bash
         run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
-        id: extract_tag
-
+      
   build-docker-container:
     needs: archive-build-artifacts
     uses: ./.github/workflows/reusable-build-docker-container.yml
